//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calculations
    {
        public int id { get; set; }
        public Nullable<int> idAccident { get; set; }
        public Nullable<int> idDateis { get; set; }
        public Nullable<int> idExperience { get; set; }
    
        public virtual Accident Accident { get; set; }
        public virtual DateIs DateIs { get; set; }
        public virtual Experience Experience { get; set; }
    }
}
