//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insurance_Service.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Law
    {
        public string idLaw { get; set; }
        public Nullable<int> idClient { get; set; }
        public Nullable<System.DateTime> DateIssue { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Region { get; set; }
        public string TPAuthority { get; set; }
        public Nullable<int> idTypeCategory { get; set; }
    
        public virtual CategoryType CategoryType { get; set; }
        public virtual Client Client { get; set; }
    }
}
